services:
  - type: web
    name: gestar-bem-api
    env: python
    buildCommand: pip install -r requirements.txt && python download_fonts.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
